// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeExplanation(arg1:string,arg2:string):Promise<string>;

export function ConnectChatGPTOAuth():Promise<void>;

export function GetProviderType():Promise<string>;

export function SetProvider(arg1:string,arg2:string):Promise<void>;
