// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeExplanation(arg1:string,arg2:string):Promise<string>;

export function ConnectChatGPTOAuth():Promise<void>;

export function ContinueConversation(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function GetSessionID():Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetProvider(arg1:string,arg2:string):Promise<void>;
