// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeExplanation(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeExplanation'](arg1, arg2);
}

export function ConnectChatGPTOAuth() {
  return window['go']['main']['App']['ConnectChatGPTOAuth']();
}

export function GetProviderType() {
  return window['go']['main']['App']['GetProviderType']();
}

export function SetProvider(arg1, arg2) {
  return window['go']['main']['App']['SetProvider'](arg1, arg2);
}
